name: openc4
services:
  openc4:
    build: .
    container_name: openc4
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOST=0.0.0.0

  structurizr:
    image: structurizr/structurizr:latest
    container_name: structurizr-playground
    command: [ "playground" ]
    ports:
      - "8080:8080"
    restart: unless-stopped
